defaults : &defaults
  host: "127.0.0.1"
  adapter: "postgres"
  user: "postgres"
  migration_files_path: "db/migrations" # this is the default location for all migrations

development:
  db: hello_amber_development
  <<: *defaults

test:
  db: hello_amber_test
  <<: *defaults
